apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w4vta3a3w-dotnet-basic
  janus-idp.io/tekton: w4vta3a3w-dotnet-basic
  backstage.io/kubernetes-id: w4vta3a3w-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w4vta3a3w-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
